usingSystem;
usingSystem.Collections.Generic;
usingSystem.ComponentModel;
usingSystem.Data;
usingSystem.Drawing;
usingSystem.Text;
usingSystem.Windows.Forms;
usingSystem.IO;

publicclassForm1:Form
{
privateSystem.Windows.Forms.ListViewbrowserListView;
privateSystem.Windows.Forms.LabelcurrentLabel;
privateSystem.Windows.Forms.LabeldisplayLabel;
privateSystem.Windows.Forms.ImageListfileFolder;

stringcurrentDirectory=Directory.GetCurrentDirectory();

publicForm1(){
InitializeComponent();
ImagefolderImage=Image.FromFile(winter.jpg);
ImagefileImage=Image.FromFile(winter.jpg);

fileFolder.Images.Add(folderImage);
fileFolder.Images.Add(fileImage);

LoadFilesInDirectory(currentDirectory);
displayLabel.Text=currentDirectory;
}

privatevoidbrowserListView_Click(objectsender,EventArgse)
{
if(browserListView.SelectedItems.Count!=0)
{
if(browserListView.Items[0].Selected)
{
DirectoryInfodirectoryObject=newDirectoryInfo(currentDirectory);

if(directoryObject.Parent!=null)
LoadFilesInDirectory(directoryObject.Parent.FullName);
}else{
stringchosen=browserListView.SelectedItems[0].Text;
if(Directory.Exists(currentDirectory+@\+chosen))
{
if(currentDirectory==@C:\)
LoadFilesInDirectory(currentDirectory+chosen);
else
LoadFilesInDirectory(currentDirectory+@\+chosen);
}
}
displayLabel.Text=currentDirectory;
}
}
publicvoidLoadFilesInDirectory(stringcurrentDirectoryValue)
{
try
{
browserListView.Items.Clear();
browserListView.Items.Add(GoUpOneLevel);

currentDirectory=currentDirectoryValue;
DirectoryInfonewCurrentDirectory=newDirectoryInfo(currentDirectory);

DirectoryInfo[]directoryArray=newCurrentDirectory.GetDirectories();
FileInfo[]fileArray=newCurrentDirectory.GetFiles();

foreach(DirectoryInfodirindirectoryArray)
{
ListViewItemnewDirectoryItem=browserListView.Items.Add(dir.Name);
newDirectoryItem.ImageIndex=0;
}

foreach(FileInfofileinfileArray)
{
ListViewItemnewFileItem=browserListView.Items.Add(file.Name);
newFileItem.ImageIndex=1;
}
}catch(UnauthorizedAccessException){
Console.WriteLine(UnauthorizedAccessException);
}
}
privatevoidInitializeComponent()
{
this.browserListView=newSystem.Windows.Forms.ListView();
this.fileFolder=newSystem.Windows.Forms.ImageList(newSystem.ComponentModel.Container());
this.currentLabel=newSystem.Windows.Forms.Label();
this.displayLabel=newSystem.Windows.Forms.Label();
this.SuspendLayout();
//
//browserListView
//
this.browserListView.Location=newSystem.Drawing.Point(12,60);
this.browserListView.Name=browserListView;
this.browserListView.Size=newSystem.Drawing.Size(456,197);
this.browserListView.SmallImageList=this.fileFolder;
this.browserListView.TabIndex=0;
this.browserListView.View=System.Windows.Forms.View.List;
this.browserListView.Click+=newSystem.EventHandler(this.browserListView_Click);
//
//fileFolder
//
this.fileFolder.ColorDepth=System.Windows.Forms.ColorDepth.Depth8Bit;
this.fileFolder.ImageSize=newSystem.Drawing.Size(16,16);
this.fileFolder.TransparentColor=System.Drawing.Color.Transparent;
//
//currentLabel
//
this.currentLabel.AutoSize=true;
this.currentLabel.Font=newSystem.Drawing.Font(MicrosoftSansSerif,12F,System.Drawing.FontStyle.Regular,System.Drawing.GraphicsUnit.Point,((byte)(0)));
this.currentLabel.Location=newSystem.Drawing.Point(10,19);
this.currentLabel.Name=currentLabel;
this.currentLabel.Size=newSystem.Drawing.Size(122,20);
this.currentLabel.TabIndex=1;
this.currentLabel.Text=NowinDirectory:;
//
//displayLabel
//
this.displayLabel.AutoSize=true;
this.displayLabel.Location=newSystem.Drawing.Point(138,19);
this.displayLabel.Name=displayLabel;
this.displayLabel.Size=newSystem.Drawing.Size(0,0);
this.displayLabel.TabIndex=2;
//
//ListViewTestForm
//
this.AutoScaleDimensions=newSystem.Drawing.SizeF(6F,13F);
this.AutoScaleMode=System.Windows.Forms.AutoScaleMode.Font;
this.ClientSize=newSystem.Drawing.Size(480,270);
this.Controls.Add(this.displayLabel);
this.Controls.Add(this.currentLabel);
this.Controls.Add(this.browserListView);
this.Name=ListViewTestForm;
this.Text=ListViewTest;
this.ResumeLayout(false);
this.PerformLayout();

}
[STAThread]
staticvoidMain()
{
Application.EnableVisualStyles();
Application.Run(newForm1());
}

}
